components:
  schemas:
    EvaluateMovesRequest:
      properties:
        hash:
          title: Hash
          type: string
        pgn:
          title: Pgn
          type: string
      required:
      - pgn
      title: EvaluateMovesRequest
      type: object
    Evaluation:
      properties:
        move:
          title: Move
          type: string
        score:
          title: Score
          type: integer
        score_change:
          title: Score Change
          type: integer
      required:
      - move
      title: Evaluation
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    SearchRequest:
      properties:
        color:
          title: Color
          type: string
        name:
          title: Name
          type: string
        username_chess_com:
          title: Username Chess Com
          type: string
      title: SearchRequest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: My Application
  version: 1.0.0
openapi: 3.0.2
paths:
  /evaluate_moves:
    post:
      operationId: evaluate_moves_evaluate_moves_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluateMovesRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Evaluation'
                title: Response Evaluate Moves Evaluate Moves Post
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Evaluate Moves
  /games:
    post:
      operationId: search_games_games_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Search Games
  /generate-openapi-yaml:
    get:
      operationId: generate_openapi_yaml_generate_openapi_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Generate Openapi Yaml
