components:
  schemas:
    ChessColor:
      description: An enumeration.
      enum:
      - white
      - black
      title: ChessColor
      type: string
    EvaluateMovesRequest:
      properties:
        pgn_id:
          title: Pgn Id
          type: string
      title: EvaluateMovesRequest
      type: object
    Evaluation:
      properties:
        pgn_with_score_change:
          description: PGN with score change. Only showing score change if change
            ? 15
          title: Pgn With Score Change
          type: string
      required:
      - pgn_with_score_change
      title: Evaluation
      type: object
    GameInfo:
      properties:
        black:
          title: Black
          type: string
        date:
          title: Date
          type: string
        link:
          title: Link
          type: string
        opening:
          title: Opening
          type: string
        pgn_id:
          title: Pgn Id
          type: string
        result:
          title: Result
          type: string
        white:
          title: White
          type: string
      required:
      - date
      - white
      - black
      - result
      - opening
      - pgn_id
      - link
      title: GameInfo
      type: object
    GenerateGifGameRequest:
      properties:
        pgn_data:
          title: Pgn Data
          type: string
        pgn_id:
          title: Pgn Id
          type: string
        reverse:
          default: false
          title: Reverse
          type: boolean
      title: GenerateGifGameRequest
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    SearchRequest:
      properties:
        color:
          $ref: '#/components/schemas/ChessColor'
        name:
          title: Name
          type: string
        opening:
          title: Opening
          type: string
      title: SearchRequest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: My Application
  version: 1.0.0
openapi: 3.0.2
paths:
  /evaluate_moves:
    post:
      description: Always return a markdown table containing the worst moves made
        by each player (player|move|score_change)
      operationId: evaluate_moves_evaluate_moves_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluateMovesRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Evaluate Moves
  /games:
    post:
      description: Search for games by player name, color, or opening. Always return
        the link as clickable.
      operationId: search_games_games_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GameInfo'
                title: Response Search Games Games Post
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Search Games
  /generate-gif-game/:
    post:
      description: Generate a gif game from a PGN file. Use reverse if player is black.
        Embed the gif in markdown with ![]({url})
      operationId: generate_gif_game_generate_gif_game__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateGifGameRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Generate Gif Game
  /generate-openapi-yaml:
    get:
      operationId: generate_openapi_yaml_generate_openapi_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Generate Openapi Yaml
